[build]
  command = "make build"
  functions = "functions"
  publish = "public"

[context.production.environment]
HUGO_VERSION = "0.79.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[headers]]
 for = "/*"
  [headers.values]
   Access-Control-Allow-Origin = "*"
   X-Frame-Options = "DENY"
   X-XSS-Protection = "1; mode=block"
   Referrer-Policy = "no-referrer"
   X-Content-Type-Options = "nosniff"
   Link = "</crg.css>; rel=preload; as=style"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[redirects]]
  from = "/api/uuid"
  to = "/.netlify/functions/uuid"
  status = 200
  force = true

[[redirects]]
  from = "/api/ip"
  to = "/.netlify/functions/ip"
  status = 200
  force = true

[[redirects]]
  from = "/api/whoami"
  to = "/.netlify/functions/whoami"
  status = 200
  force = true

[[redirects]]
  from = "/api/whoami-json"
  to = "/.netlify/functions/whoami-json"
  status = 200
  force = true

[[redirects]]
  from = "/api/whoami-jsonp"
  to = "/.netlify/functions/whoami-jsonp"
  status = 200
  force = true

[[redirects]]
  from = "/api/whoami-xml"
  to = "/.netlify/functions/whoami-xml"
  status = 200
  force = true

[[redirects]]
  from = "/api/whoami-xmlp"
  to = "/.netlify/functions/whoami-xmlp"
  status = 200
  force = true

[[redirects]]
  from = "/discord"
  to = "https://discord.gg/grq2qwpZeS"
  status = 200
  force = true

